name: CanvasClaims
version: 0.1
description: This is a claims management plugin
author: ZombieHippie
authors: [CornyZombie, zerdang]
database: false

main: com.zombiehippie.bukkit.claims.CanvasClaims

commands:
  AbandonClaim:
    description: Abandon the claim you are standing in.
    aliases: [abandonclaim, abandon, deleteclaim, unclaim, ac]
    permission: claims.abandon
    usage: Stand in your claim and type /&lt;command&gt; to abandon it.
  ClaimInfo:
    description: List info regarding your claim stats 
    aliases: [claims, claiminfo, ci]
    permission: claims.info
    usage: Type /&lt;command&gt; to list the amount of blocks you have for claiming and other info
  ClaimWarp:
    description: Warp to a owned claim
    aliases: [cw]
    permission: claims.warp
    usage: |
        Type /&lt;command&gt; to list your claims
        Type /&lt;command&gt; {claim_id} to warp to a claim

permissions:
  claims.*:
    description: Gives access to all Inferno commands
    children:
      claims.claim: true
      claims.abandon: true
      claims.info: true
      claims.warp: true
  claims.claim:
    description: Allows you to make a claim
    default: true
  claims.abandon:
    description: Allows you to abandon a claim
    default: true
  claims.info:
    description: Allows you to view claim info
    default: true
  claims.warp:
    description: Allows you to warp to various claims
    default: false