name: Canvas Painter
version: 0.1
description: This is a construction utility
author: ZombieHippie
authors: [CornyZombie, ChineseZombie]
depend: [CanvasClaims]

main: com.zombiehippie.bukkit.painter.CanvasPainter
database: false